name: Lint Source Code

on: [pull_request]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Lint
        uses: psf/black@stable
