name: Lint (black)

on: [pull_request]

jobs:
  black:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - uses: psf/black@stable
