name: Lint Source Code
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
      - name: Lint (black)
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./ally"
